### ISSUE TITLE
Update R4R API to use Elasticsearch 7.x

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/r4r-api#15]
Update API to use Elasticsearch 7.9

Related ticket: 
R4R Loader Update - https://github.com/NCIOCPL/r4r-loader/issues/8

Needs more task breakout - but this one does not use templates.

Tasks:
1.
2.

**Comment by blairlearn** [comment]
Completed in 55f873390118c34edfedcc16182472709c3b1ea1
